import VersoManual
import Content.Meta

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open Verso.Code.External

set_option verso.exampleProject "."
set_option verso.exampleModule "Content.ListProofs"

#doc (Manual) "Lists" =>

If you have already used a functional programming language like
Haskell you know that lists are a very ubiquitous datastructure. Given
`A : Type` there is `List A : Type` which is the type of
finite sequences of elements of `A`. So for example `[1,2,3] : list
ℕ` or `[true] : List Bool`, we can also have lists of lists so for
example `[[],[0],[0,1],[0,1,2]] : List (List ℕ)` is a list of lists
of numbers. However, all elements of a list must have the same type,
hence something like `[1,tt]` is not permitted.

For any type `A` we always can construct the empty list `[] : List
A`, which is also called `nil` (this comes from the phrase *not in
list* and it was used in the first functional language LISP which was
first implemented in 1959). On the other hand if we have an element `a :
A` and a list `l : List A` we can form the list `a :: l : list A` with
`a` in front of `l`, e.g. `1 :: [2,3] = [1,2,3]`.  We call this
`cons` - another heritage from LISP. Indeed the notation using
`[ .. ]` is just a short-hand, e.g.::
```
  [1,2,3] = 1 :: 2 :: 3 :: []
```
or using `nil` and `cons`::
```
  = cons 1 (cons 2 (cons 3 nil))
```
All lists can be created from `nil` and `cons` hence lists can be
defined inductively in a manner very similar to `ℕ`
```anchor ListDef
inductive List(A : Type) : Type where
| nil : List A
| cons : A → List A → List A
```
This declaration means:

- For any type `A : Type` There is a new type `List A : Type`,
- There are elements `nil : list A`, and given `a : A` and `l :
  list A` we have
  `cons a l`.
- All the elements of `List A` can be generated by `nil` and then
  applying `cons` a finite number of times,
- `nil` and `cons a l` are different elements,
- `cons` is injective, i.e. given `cons a as = cons b bs` then we know
  that `a = b` and `as = bs`.

# Basic properties of `List`

Most of the basic properties and their proofs are very similar to the natural numbers. First of all we
want to show that `[] ≠ a :: l` which corresponds to `0 ≠
succ n` and `true ≠ false` we had seen before. These properties are
called *no confusion properties*. We can use `cases` as
before for natural numbers:
```anchor noConf
theorem noConf : ∀ a : A , ∀ as : List A, [] ≠ a :: as := by
intro a as h
cases h
```
We can use the injection tactic to prove the injectivity of cons in both arguments:
```anchor injCons
theorem injCons_1 : ∀ a b : A, ∀ as bs : List A, a :: as = b :: bs → a = b := by
intro a b as bs h
injection h

theorem injCons_2 : ∀ a b : A, ∀ as bs : List A, a :: as = b :: bs → as = bs := by
intro a b as bs h
injection h
```

As before for `ℕ` we can prove `injCons_2` from first principles using `tl` (tail)
```anchor tl
def tl : List A → List A
| [] => []
| _ :: as => as
```
but it isn't so obvious what to do for `injCons_1` because we cannot complete the definition for `hd` (head) :
```anchor hd
def hd : List A → A
| [] => sorry
| a :: as => a
end hd
```
There is no defaullt element we can use to replace `sorry` - indeed the type `A` could be empty. I leave it as a challenge to prove `injCons_1` without using `injection`.

# Induction for Lists

Induction for lists works very similar as for natural numbers: to prove a property for all lists `List A` we prove it for `[]` and we show that if it holds for a list `as` then it also holds for `a :: as` for any `a : A`.

We define the length function and append for lists and show by inudction that the length of append is the sum of lengths. Ok let's start with `length` which is an easy recursion on lists:

```anchor length
def length : List A → ℕ
| [] => 0
| a :: as => succ (length as)
```

Now `append` is very similar to `+` but this time we do recursion on the first argument (why?).

```anchor append
def append : List A → List A → List A
| [] , as => as
| a :: as , bs => cons a (append as bs)
```

We adopt the usual notation writing `as ++ bs` for `append as bs`. Now we can state and prove the theorem that `length (as ++ bs)` is equal to `length as + length bs`.

```anchor length_append
theorem length_append : ∀ as bs : List A , length (as ++ bs) = length as + length bs := by
intro as bs
induction as with
| nil =>
    calc length ([] ++ bs)
      = length bs := by rfl
    _ = 0 + length bs := by rw [add_lneutr]
    _ = length []+length bs := by rfl
| cons a as ih =>
    calc length (a :: as ++ bs)
       = length (a :: (as ++ bs)) := by rfl
       _ = succ (length (as ++ bs)) := by rfl
       _ = succ (length as + length bs) := by rw [ih]
       _ = succ (length as) + length bs := by rw [← NatProofs.add_succ]
       _ = length (a :: as) +length bs := by rfl
```

In the inductive step we are using the induction hypothesis `length (as ++ bs) = length as+length bs` to prove `length (a :: as ++ bs) = length (a :: as)+length bs`.

This would be easier if addition and append would be defined by recursion over the same argument but here we need to exploit the lemmas we needed to show commutativity of addition.

Actually another approach would be to prove a different version of `length_append` which swaps the order and then use commutativity of `+` to derive the original theorem. I leave it as an exercise to complete the proof udsing list induction:

```anchor length_append'
theorem length_append' : ∀ as bs : List A , length (as ++ bs) = length bs + length as :=
by sorry
```

# The free monoid

In the section on natural numbers we encountered a *monoid* using
`+` and `0` on `ℕ`. There is a very similar monoid for lists
using `++` and `[]`.

In the definition of `append` we are using pattern matching and
structural recursion on lists. This works in the same way as for
natural numbers: we can recursively use `append` for the smaller
list `as`. To prove that this forms a monoid we need
induction. However, different from `+`, now left neutrality is easy
because it follows from the definition:

```anchor app_lneutr
theorem app_lneutr : forall as : List A, [] ++ as = as := by
intro as
rfl
```

But now right neutrality requires induction:

```anchor app_rneutr
theorem app_rneutr : forall as : List A, as ++ [] = as := by
intro as
induction as with
| nil =>
  rfl
| cons a as ih =>
  calc
    a :: as ++ []
    = a :: (as ++ []) := by rfl
    _ = a :: as := by rw [ih]
```

The switch between left and right neutrality is a consequence of that we
have defined `+` by recursion over the 2nd argument while we have
defined `++` by recursion over the first. We could have defined
`+` by recursion over the first argument and then this difference
would have disappeared (I prefer this but the designers of the lean
standard library had different ideas). We couldn't have defined `++`
by recursion over the 2nd argument - do you see why?

The proof of associativity of `++` again is very similar to the one
for `+`. The main difference is that now we do induction over the
first argument instead of the last - again this is caused by the fact
that we now use recursion over the first instead of the 2nd argument.

```anchor app_assoc
theorem app_assoc :  forall as bs cs : List A, (as ++ bs) ++ cs = as ++ (bs ++ cs) := by
intro as bs cs
induction as with
| nil =>
  rfl
| cons a as ih =>
  calc
    (a :: as ++ bs) ++ cs
      = a :: ((as ++ bs) ++ cs) := by rfl
    _ = a :: (as ++ (bs ++ cs)) := by rw [ih]
    _ = a :: as ++ (bs ++ cs) := by rfl
```

For `+` we also proved commutativity that is `m + n = n + m`, but
clearly this doesn't hold for `++`, e.g. `[1,2] ++ [3,4] =
[1,2,3,4]` while `[3,4] ++ [1,2] = [3,4,1,2]`.

Indeed `List A` with `++` and `[]` is the *free monoid* over
`A` which intuitively means that only the monoid equations hold but no
additional laws like commutativity. In this sense this monoid is free
not to follow any laws apart from the monoid ones.
