import VersoManual
import Content.Meta

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open Verso.Code.External

set_option verso.exampleProject "."
set_option verso.exampleModule "Content.NatProofs"

#doc (Manual) "The Natural Numbers" =>

We have already used the natural numbers (`ℕ`) in examples but now
we will formally define them. We will in spirit follow Guiseppe Peano who
codified the laws of natural numbers using predicate logic in the late
19th century. This is referred to as *Peano Arithmetic*.

![Giuseppe Peano (1858–1932)](diagrams/peano.jpg)
*Giuseppe Peano (1858–1932)*

Peano viewed the natural numbers as created from `zero` (`0 = zero`) and `succ`
(successor), i.e. `1 = succ 0`, `2 = succ 1` and so on. In Lean this corresponds to the following inductive definition:
```anchor NatDef
inductive Nat : Type
| zero : Nat
| succ : Nat → Nat
```
This declaration means:

* There is a new type `Nat : Type`,
* There are two elements `zero : nat`, and given `n : nat` we have `succ n : nat`,
* All the elements of `nat` can be generated by `zero` and then applying `succ` a finite number of times,
* `zero` and `succ n` are different elements,
* `succ` is injective, i.e. given `succ m = succ n` then we know that `m = n`.

We adopt the notation that `ℕ = nat`, and Lean also automatically translates the usual decimal notation into elements of `ℕ`. This is convenient because otherwise it would be quite cumbersome to write out a number like `1234 : ℕ`.

# Basic properties of `ℕ`

## No confusion

Let's verify some basic properties of `ℕ` which actually correspond to some of Peano's axioms. First of all we want to verify that `0 ≠ succ n`, which corresponds to `true ≠ false` for `Bool` and indeed the same approach works here.
```anchor NoConf
example : ∀ n : ℕ , succ n ≠ zero := by
intro n h
cases h
```
I leave it as an exercise to establish this *no confusion property* from first principles as we have done for `Bool`.

## `succ` is injective

Next let's show that `succ` is injective. To do this we define a predecessor function `pred` using pattern matching, which works the same way as for `bool`:
```anchor pred
def pred : ℕ → ℕ
| zero => zero
| succ n => n
```
We can test the function using `#reduce (pred 7)`.

We defined `pred 0 = 0` which is a bit arbitrary. However, `pred` does the job to show that `succ` is injective:
```anchor succInj
example : ∀ m n : ℕ, succ m = succ n → m = n := by
intro m n h
change pred (succ m) = n
rw [h]
rfl
```
Here we use `change` to replace the goal `m = n` with `pred (succ m) = n` exploiting that `pred (succ x) = x`. On the new goal we can apply `rw`.

However, there is also a tactic called `injection` which does this automatically for all inductive types, avoiding the need to define `pred`:
```anchor succInj2
example : ∀ m n : ℕ, succ m = succ n → m = n := by
intro m n h
injection h
```

# Structural recursion

When defining functions on `ℕ` we will need recursion. Unlike the general recursion available in programming languages, we will only use *structural recursion*. That is, when we define a function on the natural numbers we can use the function on `n` to compute it for `succ n`. A simple example is the `double` function, which doubles a number:
```anchor double
def double : ℕ → ℕ
| zero => zero
| succ n => succ (succ (double n))
```
Here `double (succ n)` is `succ (succ (double n))`. That is, every `succ` is replaced by two `succ`s.

Because every natural number can be obtained by applying `succ` a finite number of times, recursive functions like this terminate in a finite number of steps. Non-terminating definitions, such as
```
def bad : ℕ → ℕ
| zero => zero
| succ n => succ (bad (succ n))
```
are rejected by Lean, since they don't define a mathematical function on `ℕ`.

We can define the inverse to `double` (division by 2 without remainder):
```anchor half
def half : ℕ → ℕ
| zero => zero
| succ zero => zero
| succ (succ n) => succ (half n)
```

Here `half` replaces every two `succ`s by one.

# Induction

Proof by induction is very closely related to structural recursion. It is basically the same idea, but for proofs. As an example, let's actually prove that `half` is the inverse of `double`:
```anchor halfDouble
theorem half_double :
  ∀ n : ℕ, half (double n) = n := by
intro n
induction n with
| zero => rfl
| succ n ih =>
    calc
      half (double (succ n))
      = half (succ (succ (double n))) := by rfl
      _ = succ (half (double n)) := by rfl
      _ = succ n := by rw [ih]
```
After `intro n` we are in the following state:

```
n : ℕ
⊢ half (double n) = n
```

`induction n` works very similarly to `cases`, but it gives us an extra assumption in the successor case—the *induction hypothesis*. That is in the `succ` case we have an extra argument (which I call `ih` for *induction hypothesis*).
```
m : ℕ
ih : half (double m) = m
⊢ half (double (m + 1)) = m + 1
```
This means that we can assume the statement for `m` when proving it for `succ m` (which is displayed as `m + 1`.)

We prove this in several steps using `calc`, staring with
```
half (double (succ n))
```
we apply the definition of `double` (by saying `rfl`):
```
= half (succ (succ (double n))) := by rfl
```
and now the definition of `half` (again using `rfl`)
```
_ = succ (half (double n)) := by rfl
```
The `_` is just an indicator for lean that we are chaining equations.
Now we have a term that matches the induction hypothesis and we can just rewrite:
```
_ = succ n := by rw [ih]
```
and we are done.

This is a very simple inductive proof, but it shows the general idea. Because every number is finitely generated from `zero` and `succ`, we can *run* an inductive proof for any number by repeating the inductive step as many times as there are `succ`s.

Induction is the main workhorse for proving properties of inductive types like `ℕ`. Try to fully understand the idea by looking at the simple proof above!

# Addition and its properties

While addition is an operation which you may have learned already in
kindergarten, it still needs to be defined. And, horror, its definition
already uses recursion — they don't tell the kids this in kindergarten!

Here is Lean's definition of addition :
```anchor add
def add : ℕ → ℕ → ℕ
| m  , zero     => m
| m  , (succ n) => succ (add m n)
```
`add m n` applies `n` successors to `m`. We define `m + n` as
`add m n`. For example:
```
3 + 2
= add 3 2
= add 3 (succ 1)
= succ (add 3 1)
= succ (add 3 (succ 0))
= succ (succ (add 3 0))
= succ (succ (add 3 zero))
= succ (succ 3)
= 5
```

Lean also introduces the usual notation that `m + n` is defined as `add m n`.

Lean defines addition by recursion over the second argument. While it
might seem more natural to recurse over the first argument, the result
is the same because addition is commutative (`m + n = n + m`), as we
will show soon. We will stick with Lean’s convention for now.

Now, what are the basic algebraic properties of `+`?

First of all, `0` is a *neutral element*, meaning `n + 0 = n` and
`0 + n = n`. You might think we only need to prove one of them since
addition is commutative, but we actually need both when proving
commutativity. It turns out that one is trivial, while the other
requires induction.

The theorem `add_rneutr` (`n + 0 = n`) holds by definition of `add`.
```anchor add_rneutr
theorem add_rneutr : ∀ n : ℕ, n + 0 = n := by
intro n
rfl
```

However, `add_lneutr` (`0 + n = n`) does require induction.
```anchor add_lneutr
theorem add_lneutr : ∀ n : ℕ, 0 + n  = n := by
intro n
induction n with
 | zero => rfl
 | succ m ih =>
     calc 0 + (succ m)
          = succ (0 + m)  := by rfl
          _ = succ m := by rw [ih]
```

This asymmetry comes from the definition of `+` (`add`) by recursion over the 2nd argument. If we had defined it by recursion of the first it would be the other way around.

Another important property of addition is that brackets don’t matter:
`(l + m) + n = l + (m + n)`. This is called *associativity*.
We again need induction, but the variable we choose for induction
matters. Since addition is defined by matching on its second argument,
we must perform induction on that argument (`n`).
```anchor add_assoc
theorem add_assoc : ∀ l m n : ℕ , (l + m) + n = l + (m + n) := by
intro l m n
induction n with
| zero => rfl
| succ n' ih =>
     calc  (l + m) + (succ n')
         = succ ((l + m) +n') := by rfl
      _  = succ (l + (m + n')) := by rw [ih]
      _  = l + (succ (m + n')) := by rfl
      _  = l + (m + (succ n')) := by rfl
```

In the base case (`n = 0`), both sides reduce to `l + m`.
In the successor case, we are able to push through `succ` on both sides (using jsut the definition of `+`) to be able to apply the induction hypothesis.

We have now shown the following facts about `+` and `0`:

* `0` is right neutral: `n + 0 = n` (`add_rneutr`),
* `0` is left neutral: `0 + n = n` (`add_lneutr`),
* `+` is associative: `(l + m) + n = l + (m + n)` (`add_assoc`).

Such a structure is called a *monoid*.
(If you look up "monoid" on Wikipedia, don’t be distracted by the
philosophical concept of the same name!)

However, we have not yet discussed *commutativity* (`l + m = m + l`) , which isn’t
required for a monoid.

To prove commutativity, it isn't clear on which variable to do induction because both appear in different positions. So we may as well do induction on the second (`m`) so that the left hand side reduces. The zero case can be proven using `l_neutr` which but the successor case is more difficult: our induction hypothesis is `ih : l + m = m + l` and we want to show `l + succ m = succ m + l`. We reason:
```
        l + (succ m)
           = succ (l + m) := by rfl
```
and now we can already apply the induction hypothesis:
```
         _ = succ (m + l) := by rw[ih]
```
but how do we bridge the gap to `succ (m + l)`? This is a common situation when proving theorems, which is a bit like using stepping stones to cross a stream. We need to put an additional stone in which in this case is a *lemma* (i.e. an auxilliary theorem), which can be proven by induction:
```anchor add_succ
theorem add_succ :
∀ l m : ℕ, (succ l) + m = succ (l + m) := by
intro l m
induction m with
 | zero => rfl
 | succ m ih =>
     calc
       (succ l) + (succ m)
         = succ ((succ l ) + m) := by rfl
       _ = succ (succ (l + m)) := by rw [ih]
       _ = succ (l + succ m) := by rfl
```
We can now use our *stepping stone* to prove commutativity:
```anchor add_comm
theorem add_comm :
∀ l m : ℕ, l + m = m + l := by
intro l m
induction m with
| zero =>
    calc l + 0
        = l := by rfl
      _ = 0 + l := by rw [add_lneutr]
| succ m ih =>
      calc   l + (succ m)
           = succ (l + m) := by rfl
         _ = succ (m + l) := by rw[ih]
         _ = (succ m) + l := by rw [← add_succ]
```

The lemmas we needed to prove commutativity of addition are just the mirror image of the equation which follow from the definition, that is by definition we have that
```
m + 0 = m
m + (succ n) = succ (m + n)
```
and for commutativity we need to establish
```
0 + m = m
(succ m) + n = succ (m + b)
```
Together with the previous results, we have now established that
`ℕ` with `+` and `0` forms a *commutative monoid*.
