import VersoManual
import Content.Meta

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open Verso.Code.External

set_option verso.exampleProject "."
set_option verso.exampleModule "Content.NatProofs"

#doc (Manual) "The Natural Numbers" =>

We have already used the natural numbers (`ℕ`) in examples but now
we will formally define them. We will in spirit follow Guiseppe Peano who
codified the laws of natural numbers using predicate logic in the late
19th century. This is referred to as *Peano Arithmetic*.

![Giuseppe Peano (1858–1932)](diagrams/peano.jpg)
*Giuseppe Peano (1858–1932)*

Peano viewed the natural numbers as created from `zero` (`0 = zero`) and `succ`
(successor), i.e. `1 = succ 0`, `2 = succ 1` and so on. In Lean this corresponds to the following inductive definition:
```anchor NatDef
inductive Nat : Type
| zero : Nat
| succ : Nat → Nat
```
This declaration means:

* There is a new type `Nat : Type`,
* There are two elements `zero : nat`, and given `n : nat` we have `succ n : nat`,
* All the elements of `nat` can be generated by `zero` and then applying `succ` a finite number of times,
* `zero` and `succ n` are different elements,
* `succ` is injective, i.e. given `succ m = succ n` then we know that `m = n`.

We adopt the notation that `ℕ = nat`, and Lean also automatically translates the usual decimal notation into elements of `ℕ`. This is convenient because otherwise it would be quite cumbersome to write out a number like `1234 : ℕ`.

# Basic properties of `ℕ`

## No confusion

Let's verify some basic properties of `ℕ` which actually correspond to some of Peano's axioms. First of all we want to verify that `0 ≠ succ n`, which corresponds to `true ≠ false` for `Bool` and indeed the same approach works here.
```anchor NoConf
example : ∀ n : ℕ , succ n ≠ zero := by
intro n h
cases h
```
I leave it as an exercise to establish this *no confusion property* from first principles as we have done for `Bool`.

## `succ` is injective

Next let's show that `succ` is injective. To do this we define a predecessor function `pred` using pattern matching, which works the same way as for `bool`:
```anchor pred
def pred : ℕ → ℕ
| zero => zero
| succ n => n
```
We can test the function using `#reduce (pred 7)`.

We defined `pred 0 = 0` which is a bit arbitrary. However, `pred` does the job to show that `succ` is injective:
```anchor succInj
example : ∀ m n : ℕ, succ m = succ n → m = n := by
intro m n h
change pred (succ m) = n
rw [h]
rfl
```
Here we use `change` to replace the goal `m = n` with `pred (succ m) = n` exploiting that `pred (succ x) = x`. On the new goal we can apply `rw`.

However, there is also a tactic called `injection` which does this automatically for all inductive types, avoiding the need to define `pred`:
```anchor succInj2
example : ∀ m n : ℕ, succ m = succ n → m = n := by
intro m n h
injection h
```

# Structural recursion

When defining functions on `ℕ` we will need recursion. Unlike the general recursion available in programming languages, we will only use *structural recursion*. That is, when we define a function on the natural numbers we can use the function on `n` to compute it for `succ n`. A simple example is the `double` function, which doubles a number:
```anchor double
def double : ℕ → ℕ
| zero => zero
| succ n => succ (succ (double n))
```
Here `double (succ n)` is `succ (succ (double n))`. That is, every `succ` is replaced by two `succ`s.

Because every natural number can be obtained by applying `succ` a finite number of times, recursive functions like this terminate in a finite number of steps. Non-terminating definitions, such as
```
def bad : ℕ → ℕ
| zero => zero
| succ n => succ (bad (succ n))
```
are rejected by Lean, since they don't define a mathematical function on `ℕ`.

We can define the inverse to `double` (division by 2 without remainder):
```anchor half
def half : ℕ → ℕ
| zero => zero
| succ zero => zero
| succ (succ n) => succ (half n)
```

Here `half` replaces every two `succ`s by one.

# Induction

Proof by induction is very closely related to structural recursion. It is basically the same idea, but for proofs. As an example, let's actually prove that `half` is the inverse of `double`:
```anchor halfDouble
example : ∀ n : ℕ , half (double n) = n := by
intro n
induction n with
 | zero => rfl
 | succ m ih =>
    dsimp [double,half]
    rw [ih]
```
After `intro n` we are in the following state:

```
n : ℕ
⊢ half (double n) = n
```

`induction n` works very similarly to `cases`, but it gives us an extra assumption in the successor case—the *induction hypothesis*. That is in the `succ` case we have an extra argument (which I call `ih` for *induction hypothesis*).
```
m : ℕ
ih : half (double m) = m
⊢ half (double (m + 1)) = m + 1
```
This means that we can assume the statement for `m` when proving it for `succ m` (which is displayed as `m + 1`.)

After simplyfying the goal using `dsimp [double,half]` we have
```
m : ℕ
ih : half (double m) = m
⊢ half (double m) + 1 = m + 1
```
and we can rewrite with `oh` which solves the goal (`rfl` is applied automatically).

This is a very simple inductive proof, but it shows the general idea. Because every number is finitely generated from `zero` and `succ`, we can *run* an inductive proof for any number by repeating the inductive step as many times as there are `succ`s.

Induction is the main workhorse for proving properties of inductive types like `ℕ`.

# Addition and its properties

While addition is an operation which you may have learned already in
kindergarten, it still needs to be defined. And, horror, its definition
already uses recursion — they don't tell the kids this in kindergarten!

Here is Lean's definition of addition :
```anchor add
def add : ℕ → ℕ → ℕ
| m  , zero     => m
| m  , (succ n) => succ (add m n)
```
add m n` applies `n` successors to `m`. We define `m + n` as
`add m n`. For example:

```
3 + 2
= add 3 2
= add 3 (succ 1)
= succ (add 3 1)
= succ (add 3 (succ 0))
= succ (succ (add 3 0))
= succ (succ (add 3 zero))
= succ (succ 3)
= 5
```

Lean also introduces the usual notation that `m + n` is defined as `add m n`.

Lean defines addition by recursion over the second argument. While it
might seem more natural to recurse over the first argument, the result
is the same because addition is commutative (`m + n = n + m`), as we
will show soon. We will stick with Lean’s convention for now.

Now, what are the basic algebraic properties of `+`?

First of all, `0` is a *neutral element*, meaning `n + 0 = n` and
`0 + n = n`. You might think we only need to prove one of them since
addition is commutative, but we actually need both when proving
commutativity. It turns out that one is trivial, while the other
requires induction.




The theorem `add_rneutr` (`n + 0 = n`) holds by definition of `add`.
However, `add_lneutr` (`0 + n = n`) does require induction.
